add=str(input('Enter Text To write To The file:'))
file=open('output.txt','r+')
writing=file.write(add)
file.close()
print('data Successfully written to Output.txt')
modify=str(input('Enter additional Text To append:'))
file=open('output.txt','a')
append=file.write(modify)
file.close()
print('data Successfully appended.')
print('Final Content Of output.txt:')
file=open('output.txt','r+')
reading=file.read()
print(reading)
file.close()
